### ISSUE TITLE
synthesis samples

### ISSUE THREAD

**Issue by arunbaby0** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#1]
Do you have any synthesized samples?

**Comment by Sharad24** [comment]
We will be uploading them by the end of this month

**Comment by arunbaby0** [comment]
Great. Is it as good as the samples from the original paper?

**Comment by Sharad24** [comment]
We've trained the speaker encoder model as of now. We're currently facing an optimisation issue. The model tries to generalise one/two single voice(s) for all speakers to reduce the loss function. We'll be training it again with a few tricks that might help us get out of this situation

**Comment by Sharad24** [comment]
The synthesis samples for Speaker Adaptation approach can be found here: http://saidl.in/Neural-Voice-Cloning-With-Few-Samples/

**Comment by MNCTTY** [comment]
hello, Sharad. Page with samples is unavailable now

**Comment by Sharad24** [comment]
https://sforaidl.github.io/Neural-Voice-Cloning-With-Few-Samples/
