### ISSUE TITLE
how to run the project for our own voice ?

### ISSUE THREAD

**Issue by farooqrasheed123** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#11]
how to run the project for our own voice ? The commands given in README are to be typed in python or Anaconda command prompt or in Anaconda console ? Please guide me how to do this ?

**Comment by farooqrasheed123** [comment]
how to run the project for our own voice ? The commands given in README are to be typed in python or Anaconda command prompt or in Anaconda console ? Please guide me how to do this ?

**Comment by yyg192** [comment]
I suggest you take a look at this  https://github.com/r9y9/deepvoice3_pytorch. Here is a description of how to generate a custom dataset.
