### ISSUE TITLE
Why you set n_speakers = 1 when performing adaptation with the vctk dataset (84 speakers available)

### ISSUE THREAD

**Issue by falconjhc** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#12]
As titled, and in addition, you set self.multi_speaker = False when self.train_set==1.
Is there any reasons that drive you to do so? 
It seems to be quite strange to me.

Many thanks for your help.
Best,

Harric

**Comment by lin88lin8850** [comment]
> As titled, and in addition, you set self.multi_speaker = False when self.train_set==1.
> Is there any reasons that drive you to do so?
> It seems to be quite strange to me.
> 
> Many thanks for your help.
> Best,
> 
> Harric

Have u tried to train with n_speakers = 84?
