### ISSUE TITLE
I tried to adapt the model to a new speaker with 30 samples,but got really bad cloning result.

### ISSUE THREAD

**Issue by yyg192** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#16]
I tried to adapt the model to a new speaker with 30 samples,but got really bad cloning result. I saw that the voice clone model released by Baidu only needs one sample to get a clear voice.
Has anyone succeeded in implementing  cloning with very few samples?

**Comment by mennatallah644** [comment]
@yyg192  
would you please tell me how did you get cloning audios ? what should i do after finishing this step ?
![Capture](https://user-images.githubusercontent.com/32370077/58619555-68cdd980-82c5-11e9-88db-1e179241e257.PNG)

**Comment by YYYYWD** [comment]
@yyg192 请问你是怎么开始训练的呢？可以加我的qq2928887356告诉我一下吗，感激不尽！
