### ISSUE TITLE
Is pre-trained model available?

### ISSUE THREAD

**Issue by sdx0112** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#19]
I have a audio file from a new speaker and want to adapt the model to this speaker. So is the pre-trained model available somewhere online?

And to adapt the model to the new speaker, which parameter refers to the new audio file location as in the following cmd? 
`python speaker_adaptation.py --data-root=<path_of_vctk_dataset> --restore-parts=<path_of_checkpoint> --checkpoint-dir=<path> --checkpoint-interval=<int>`

**Comment by nikich340** [comment]
Really needed any pretrained model, especially for low-GPU users (24 hours preparing => 24 days or weeks of preparing).

Also it is strange to build model every time, as I understand once made model on many quality speakers voice is enough for cloning any new voice using this model.
So I do not understand why such a model is not available.
