### ISSUE TITLE
whole_model branch

### ISSUE THREAD

**Issue by wanshun123** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#2]
What is the status of the whole_model branch? Is that a complete implementation of the paper, or if not, what still remains to be implemented?

**Comment by mehulrastogi** [comment]
Hi i am still working on the whole_model branch.I am trying to incorporate the combined training of the encoder and the deep voice 3 there.It still has some bugs yet to be resolved

**Comment by aishweta** [comment]
@mehulrastogi is your model is working?
