### ISSUE TITLE
There is no "training.txt" in VCTK Folder

### ISSUE THREAD

**Issue by aliyesilkanat** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#21]
In speaker_adaptation.py inside _NPYDataSource.collect_files method:

` meta = join(self.data_root, "train.txt")`

That 'train.txt' does not appear on my VCTK corpus which I have downloaded from [here.](https://datashare.is.ed.ac.uk/handle/10283/2651) Should I create this file myself? If then, how should I?

**Comment by YYYYWD** [comment]
I have the same problem with you.
Can you solve this problem new? Could you give me some help?

**Comment by xuexuanyu** [comment]
It can be fixed by running preprocess.py first.
