### ISSUE TITLE
Error with single speaker adaptation

### ISSUE THREAD

**Issue by ankitsindhu** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#23]
'\torch\nn\backends\backend.py' line 11, in __getattr__

"Could not find function class for [{}]".format(name))
AttributeError: Could not find function class for [Embedding]

**Comment by Sharad24** [comment]
This seems like an internal pytorch error due to versioning and not something spawning from our work. You might be running a version higher than when the code was writtern
