### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by Menna3** [SforAiDl/Neural-Voice-Cloning-With-Few-Samples#4]
Would you please tell me how to actually clone voices using your code? After running setup.py what should I do?
Thanks in advance.

**Comment by mehulrastogi** [comment]
I will be updating the README in the coming week. It will include how to do speaker adaptation using VCTK dataset

**Comment by Sharad24** [comment]
The readme of the whole_model branch has been updated and describes how to run speaker adaptation. Link to voice samples has also been added.

**Comment by mennatallah644** [comment]
@Sharad24 
After Adapting the model to particular speaker , how to generate cloned audios to this speaker
